apiVersion: v1 
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  db_password: # here mention db_password base64 encode 
  rabbitmy_pass: # here mention rabbitmq password in base64 encode 
