apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb-container
        image: ssgaikwad/vprodatabase     
        ports:
          - name: vprodb-port
            containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db_password
                name: mysecret
        volumeMounts:
          - name: db-vol-mount
            mountPath: /var/lib/mysql

      nodeSelector:
        zone: us-west-1b
        
      volumes:
        - name: db-vol-mount
          awsElasticBlockStore:
            volumeID: vol-00b8765966dfc882f
            fsType: ext4

      initContainers:
        - name: busybox-container
          image: busybox
          args: ["sh","-c","rm -rf /var/lib/mysql/lost+found"]
          volumeMounts:
            - name: db-vol-mount
              mountPath: /var/lib/mysql

