apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    db_password: AgCli9v3AuWt3dXxtkpuPxcSxYrTGgx6znMPU+yje0MendQTJJcW36T/wbX8+LkQEa4R0NkJ7c2w4TK/DhcoYxNcVfaPzjsJ/Yo05XKHUNR720ROyoXMtuELuNmmBLQpFolND5BnJL6otxTNoJajBIqEa5Jkngu2U0o14m9XnZjjQH84W+kYgZeDXUkBX4a1kiq19u4i/weHyyva5PxTnFjLZS5TtQ1qtf4ObKeiI3UYiE6Pn6Tv7Wa8vDZEaMPg0lUrkXTpMomzVYoo5yrmZwWeHdgR0ZNoc4TJ/jx98bPx+R9Cc3B9QcsOQGnuSvZP0RiIX1Bt/CUDiEHHw9rF0oO/DIT67+tNWlsupVnW3Iuj/R/q5yV6g/m0Ai8HnUuwKj9Hk1+4JDzlFeZjmGqixdxJaOtxOvq4AWWTAmzTQPHc78nXH+cAz/cz7+pRAos35oSKRYzwWTgs/S6Qjtk+aMjE8PB42fJKiKBD1RK/GkM0zcxH8xmxGyNMGTftb/3lF6iR9RjkdNYA1pk+I4qLoCePwV2bsZOYnzXhSJ8np99jbzzOhJ/s6xKpvfs+Qdb+XPO0PC0r5BAHs2aUk4D+StYOAVQJ7qiMtBH425IevdSlVQ/ZuFPMdLLJacXK2dObgj3cxiRFXZVdirHPR615x/xc83i0Rv/uVq/kxwjd7M92036INzBaFe0uFjnEcFZzbXvo/xhKW6d3yAyc
    rabbitmy_pass: AgBOtQAblqzn1C67vldX9VluBBKle+aewTGS38SXV6eKdIi1+hrOKq8uPbdiSvp7YYdoHiDOKcbieART9CF5eq+uHX/NOu7SjhJKtQ8QLdhsIqnKIJ728SDfjhQl/jBy6TX0q+t2fzyYHNq3uVRgRqXoSK3MtYTLf6XfFB2PuA68pl8UWPx6g+av7+crD/Oj/m3f3dc5K1Z4z8h08jwsCPllmDaND55MxYHLIwZ7EpghuXMd42LXapcl4HYk+QhwkpR6W6rDcnTqvDE5u46EtM817dDMTdJfQhGtur6cSnqQ140Ensp1e94u59sPYNhegKFlEHTu/yksOLYG+z52TmXbqyUhtubLXoD2qSPZmMyjDoheX1Yr3TTa1yZf5jWcBVAfNR0xKUCwGAgZqUqsz57wAXVmEATGXltWXN3jvYWqzQtY8g9bQ/oRs11h1+Q55jFxH9G+4WdWyx2wX6ymgP1ROlwNPZ4uJV2PIZw5JwQ+gQlp2P+nRXk4kuUAAhmiAL6i5Nogm96bM8t516RcfOMiSnKC2A5ToYJTaapcsQORSPv/7S8JYh3ZyHNyqRle9A///OmIIyB+R5fGsumH/X2fyJu6R3XCkw5haIsEq6fBec3hJEf6WFs6CZ4Rxws6aHzmIsHdrCpUmjqQcV1EJO+IdeAwueN71Udou2uqlb0TRmATs78CJD2CoecRtI+v2Sk7cdPxvg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
