apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    db_password: AgC9Wq1Qb1ldeR9BWfHC45SV+8aPIfdMEdjhvXhTrAOjSCzMP3MzV1jktDiw7dsvEbUq1U+ehhxWsuYMwFgKW0VDiDwECQ5uxPaV2rBTUz0pV0l2Ac8eG+HmR/oGb5PO4DAtHmgSe4IdNMVXp7KrH/Wj83s+kpcRnQRAWc71FSKop+LBn7Ig67GUR3rPKbi4Lhkz6IeNQNFM16d5gYOOgUjCVBfEP0BNLMA5sy9ByS/EMxbLUMDjxpnkhCrHsrW77Bt821WmoO3Pz2u2uD33c3NSwSwPZL9LTVWOXiHub/bR84iOrn/LyOe3mgy12dQNpnrhVg8aAo45+Y/aL2C+5Nw5z8npNqOywROvBii4NnBFmfAymq44xfvQTosJV4jS+AyDMyJZzinuu6gqSfok+16lU8pW4mxSTary0lKyTYGZlox/AKJFGQpl3N4tGurMtDuIEHwN/vYfcBvAH/xEHRkfs2PlGGTZK9+r7fXxcFfrH6cglGZ8T8wsnqW5NmqsQk5gHyHhs2wp0xEwEKfgMefrtoYuUoUaG6EpWPz9T+P5XlwtUdlcWCGFoMH9/UPmlKQbYBKELFfE3CfN+nMtZ/bCMUvjpOl0k1Pb1VyHzgELYhGT/UzRytVPX8HuEfNbGT3/4NXMVYHfT84GSlvrK+t4LfxlNOlQTf1Tk23r3dDQ0O1o5qqAkHipeGzoPAFu6qz9jDdnTEZ5EEIM
    rabbitmy_pass: AgAozxAN9of1Njvor3oeIwaOA4rw9zqThColWr0JzgdhsMI16i1qncNH9/ZdXFF4p4UHPd4mfiQyAd86IxmCqbn+zRAVTJ0q32xOCZACyB5tvRKbAfkHVnR6tHlkwa77tZ/TpNOx49hxZneDjHqgPGi2JJb73YXqae+KsWhQbXoZfCYZuP146V98F1N3dgXU66V2pSsO1m9II6/O/IvOHZIm3GE8UesGklcU4woWvitfwj/cxQ0P6b4QaIID1Ht7xOeSvojVm6Rj4frLl/aoWAhHB77CZH8nhd1lxjPbx+JhppUoL18+yCgcYbJ1HegYxW8RCuL6iidQ/dqboZrifjhJ0GESrMaX3EJy9zrXcgXOzf8YMixbKOfpsy1ERpEewdK4T3ghXS3+v/xE/dNHFGPviJnbqHjXK6coKDz6YjVU7ZYkiUqKwG2H7pGRBasleyBsAfAkxZjyHi1GI/Mk98B57ZP3qFJilh6B4G1Eokj4KsJcexf2lY1jc+AzHtgLxh1UXJm+WR3PrX0x8b9NlM00chNJQcUavD7b8xuJMlYAHeoOOAqCtlL8QxWCqrnFUOW9sp9FJ9IBnhSJ8qX+pWs8w9eD0xSFten9uapL2V8T5HuNwunJ5DkLd8XiKq82CYAZz6D5BK10F5yGu9YFyuYu1HQn7YnRbqYLLglBcY+vvtFmXERN/x2xGx6YcQWlYZu8Rv8d2A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque

