apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    db_password: AgBJeAxsSRNm7ljjzjrD2N2dKbaYEctFKzzK3Dy/FG2b8nnwna17NFTTBi8pBPCN4z8nCgCcbAL5FhoQM41B+NlulDbkwV6WB8L+uwUoOOI8eR+ywlOmLDfWvhXzVRKVjc6VxIvRSWNfRhUWvxYlHdkFB05R0nMEgv97nc1MYZn6CazGclMHzX3fN7pKG4YMJ6kc9rEEs+LfalTx/CuUJLvvGt7tpVlcK7JukowKrY38xabF6vLAodezTKsEld6yzx8yGekyOkteTjk5LQWBIhdzBVDbIVZeT3wgbMExOxY4/ofImbRo3DIuJ7+fvpeCrzxcqIMZsWvJ/MowIDNC+cf9FzhoKcle2hwRETL2+OhER5g1SqckdxKYX9h9r1gAU52uyH/TXLf58CcT3mkvu7T81OWQJ4QBC26CvnRik6d2vET6SoVnH7rkWIDb79SKH/srcuAwAiVOp6LIVMHSbrot6TD23GUOA6ZKwcsha6hvTv7z4+COnmB8hjED4p9ZbELHWUaLH5i+AYWpFN286eI/2HYJ+iWum04NHPbKu821rWU7LcdpxESrxbhMp//xxOf5zau/IqYmfIS3yATz/BX47Dee9srNSj8BYSFPM+fqYoZWRVXQf+NYf2KxgyaUq02hrEySZ2mo4AOkVKEponcliRfmdPsakkz7ADor9xxEgxncD1/zZTGEFxLNWP5imr+ejgPSqUKOvKbQ
    rabbitmy_pass: AgAeoi8brVKS8vPZXh1gFA+FSuTw+HXKq75pCcf9izfMvzhkzVhvjazm/elKqAsMxew4t0Zv4lWi2uZv2RCTRAr+h6Hz0ZFeidETeKvbf3qiT/fU+ge4SK60c4oq4nZRFV/L/ToOblAhHXofCOGOolqeHI7gPsE+8RzbgRe8U+R5DBA3F6fMwR0zi8FCgbB3esUXUmFgJpXDkxUhGUrErQro1a6FPhChBwFMc2gyzN27U4LIZ9+Qzaf4eq+3qf3o/uh9bigeCKIccBwyMIDVDQOE3xr6U+jyHok/wVGAPbcF53bQmbEMTk71llAoBrS/Scpr0A8KBnBhSVwTcaQYy6jXcFURVZnuS66IAnol4u0QnPSIh6VXtWhjEW/opdAUNyIjwXzdg9giDNPq4xCcDvmoPuOqK7CXtU7ZpS0rb3wwX9QEPb24muAoz+ggMS13wn0VlSp4K8DVkM+qz8mH9e2oXQ94oEpe6hSf82YcfTVKLzexTv3b7ZId0LQlx9HrJ6oG8ncODnWa1zIXpoQlsTJqc12yKn7AfVBx/lkgvkaSsoPB3XWu7uEnxWz9A/1MviuJbxikBvgg/v1N1kCCl/fKerqQg92lyBvm5UWUXUsLa0Z8Hpitrm7on28ye2jESuXIOVHLCa1mvgk8G3OXOCabyg8kOCU9Q4UiE9rh8R93jpHUcP13qVCsvfNe2bghdK2q+BUn6Q==

    metadata:
      
      name: mysecret
      
    type: Opaque

